### ISSUE TITLE
Authorization scheme is not supported

### ISSUE THREAD

**Issue by ekkis** [bakapear/jsonbin.org#1]
I've followed your simple instructions but am met with the following error:

> { message:
>    'Authorization scheme (f37bf009-0000-4ae3-8782-2d3dd7c95ed6) is not supported',
>   status: 400 }

the value between parentheses is my API key (not real value), which I passed to the require.  what could be the problem?

**Comment by ekkis** [comment]
I've also tried using a bearer token, as provided to me by the jsonbin website that looks like this:
```json
{
  "token": "eyJhbGciOiJIUzI1NissInR5cCI6IkpXVCJ9.eyJCZCI6IkFDQnlrdG5aSmVVIiwicGF0aCI6InVybHMiLCJpYXQiOjE1NzgyMDk4MTksImV4cCI6MTU3ODIxMzQxxx0.CMdizgHwVGcBRhz81OuS4V-qtyX8_t7-r5P87ruUdrg",
  "exp": "1 hour",
  "path": "urls"
}
```
which I passed in as an object and also as only the "token" string, but both fail

**Comment by bakapear** [comment]
Have you tried passing the token with the actual "token" prefix? It's required for it to function properly.

Example:
```js
let key = "token f37bf009-0000-4ae3-8782-2d3dd7c95ed6"
let bin = require("jsonbin.org")(key)
```

should work

**Comment by ekkis** [comment]
bloody hell.  that works.  suggestion: either 1) let's fix the documentation so that instead of "token blah blah" we have "token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" so it's clearer that the "token" is not part of the actual token, or 2) if it's always required, let's just have the function do it.  maybe even do a validation of the token value passed.  I'd be happy to produce a PR if you'll accept it

**Comment by ekkis** [comment]
oh wait.  no.  that didn't work.  here's the actual code:
```js
var jb = require('jsonbin.org')('token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx');
jb.post('index', {val: 3}).then(console.log);
```
and what I get:

> { message: 'Unprocessable Entity', status: 422 }

though that's no longer an authorization issue.  I'm having the same problem when I use curl:
```
curl -X POST https://jsonbin.org/ekkis/blog \
      -H 'authorization: token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' \
      -d '{ url: "https://remysharp.com" }'
```

> {
>   "message": "Unprocessable Entity",
>   "status": 422
> }
>

**Comment by bakapear** [comment]
> bloody hell. that works. suggestion: either 1) let's fix the documentation so that instead of "token blah blah" we have "token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" so it's clearer that the "token" is not part of the actual token, or 2) if it's always required, let's just have the function do it. maybe even do a validation of the token value passed. I'd be happy to produce a PR if you'll accept it

I've chosen this approach so you can either login via token or via bearer if you would like to do so.
```js
require('jsonbin.org')('token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
require('jsonbin.org')('Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
```

> { message: 'Unprocessable Entity', status: 422 }

This message seems to appear when trying to get a log out of a post or patch request.

```js
;(async () => {
  await bin.delete('test') // clears entire bin
  await bin.post('test', { key: true }).then(console.log) // -> Unprocessable Entity
  await bin.get('test').then(console.log) // -> { key: true }
})()
```

I could automatically make it return the content by doing an additional get request afterwards after each post or patch function internally, but it would add an extra request not everyone might want.

But you're right I should at least update the documentation accordingly for this.

**Comment by ekkis** [comment]
yes, I see... a more explicit approach might be better:
```js
require('jsonbin.org')({token: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'})
```
with regards to the unprocessable entity issue, it's a problem with the service.  it should be fixed.  I have created a bug report: https://github.com/remy/jsonbin/issues/43

**Comment by ekkis** [comment]
thanks for supporting the module
