### ISSUE TITLE
Delete hangs

### ISSUE THREAD

**Issue by ekkis** [bakapear/jsonbin.org#2]
if I run the following:
```js
var jb = require('jsonbin.org')('token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx');

var k = 'test';
jb.post(k, [0,0]).then(() => {
    console.log('posted');
    return jb.delete(k);
})
.then(o => {
    console.log('deleted');
    console.log(o);
});
```
I never see the 'deleted' message and control is never returned to me.  it just hangs.  it does seem to delete the value but it just hangs

**Comment by bakapear** [comment]
The API endpoint itself is not responding so I can't really do anything to fix this.

**Comment by ekkis** [comment]
ah.  I'll repost there.  it's a good system but it doesn't work that well.  pity
